### ISSUE TITLE
[QUESTION]How to save consumer message in database?

### ISSUE THREAD

**Issue by maquib** [mateusjunges/laravel-kafka#59] opened 2021-12-28 13:00 UTC
@mateusjunges Hi
i am trying to save data in database but not save in database.
```php
<?php

namespace App\Handlers;

use Illuminate\Support\Facades\Log;
use Junges\Kafka\Contracts\KafkaConsumerMessage;
use App\Http\Controllers\TermsController;
use App\Model\Aquib;
use DB;

class TestHandler
{
    public function __invoke(KafkaConsumerMessage $message)
    {
        $values = array('ab' => 1);
       DB::table('test')->insert($values);

        
        $var = $message->getBody();
        Log::debug('Message received!', [
            'body' => $var,
            'headers' => $message->getHeaders(),
            'partition' => $message->getPartition(),
            'key' => $message->getKey(),
            'topic' => $message->getTopicName()
        ]);
        
        
    }
}
```

**Comment by mateusjunges** [comment] 2021-12-28 14:19
Hey @maquib does the `laravel.log` file shows the received message?

**Comment by maquib** [comment] 2021-12-29 04:25
Hi @mateusjunges Yes laravel.log file shows the received message.

**Comment by rtuin** [comment] 2021-12-29 10:54
@maquib at first glance this does not relate to `laravel-kafka`.
Can you elaborate on your question/situation? What exactly do you expect your code to do, what is actually happening, and what is the minimum amount of code that you need to reproduce this issue?

**Comment by maquib** [comment] 2021-12-29 10:58
@rtuin actually I am doing produce message and consume message. I have done produce message but If I do consume message and store message into database then nothing happen

**Comment by mateusjunges** [comment] 2021-12-29 11:45
As @rtuin said, if your message appears in logs, then it's not related to this package. I'll gladly help you, but in order to do this, i need to be able to reproduce your issue.

**Comment by AarifAbdal** [comment] 2021-12-30 05:20
@maquib can you please share the consumer's code. Because I am unable to consume the messages.

**Comment by maquib** [comment] 2022-01-01 09:39
@AarifAbdal
 public function handle(): void
    {
        $consumer = Kafka::createConsumer()
            ->subscribe('test-topic')
            ->withHandler(new TestHandler)
            ->withAutoCommit()
            ->withConsumerGroupId('test-consumer')
            ->build();

	$consumer->consume();
    }

**Comment by mateusjunges** [comment] 2022-01-02 21:35
Hey @maquib i still can't reproduce your issue. I'm closing this because it's definetely not related to this package.

**Closed by mateusjunges** 2022-01-02 21:35 UTC

**Comment by maquib** [comment] 2022-01-03 10:45
@mateusjunges issue resolved

**Comment by maquib** [comment] 2022-01-03 10:45
@mateusjunges thanks for help
