### ISSUE TITLE
[QUESTION] Problem in producer 

### ISSUE THREAD

**Issue by mhbm** [mateusjunges/laravel-kafka#85] opened 2022-03-14 21:20 UTC
I need to producer message in Kafka, but I need to get SASL OAuth and I need to pass a Certificate.

I tried to use but always returns error.

SSL handshake failed: error:1416F086:SSL routines:tls_process_server_certificate:certificate verify failed: broker certificate could not be verified, verify that ssl.ca.location is correctly configured or root CA certificates are installed (brew install openssl) (after 28ms in state SSL_HANDSHAKE, 1 identical error(s) suppressed)
Sent messages may not be completed yet.12%

Could you help me?

**Comment by mateusjunges** [comment] 2022-03-21 13:33
@mhbm sorry for my late response. Can you please add the code you are using, so i can reproduce your issue?

**Comment by mateusjunges** [comment] 2022-04-06 04:45
Closing this due to lack of updates.

**Closed by mateusjunges** 2022-04-06 04:45 UTC
