### ISSUE TITLE
`stopAfterLastMessage()` not working v1.13.4

### ISSUE THREAD

**Issue by minhchau2605** [mateusjunges/laravel-kafka#226] opened 2023-10-12 07:15 UTC
Hello,
I'm using laravel v10, php 8, mateusjunges/laravel-kafka v1.13.4

Using this code to consume a topic, that using Redpanda tool and I can see many messages:
![image](https://github.com/mateusjunges/laravel-kafka/assets/27195377/a15d05cf-ce5e-474e-bcc5-30b820bc08f7)

![image](https://github.com/mateusjunges/laravel-kafka/assets/27195377/05ea64a7-424c-4079-99af-dac1ac49d4b7)

```php
$topic = config('kafka.fds_loss_topic');
$broker = config('kafka.brokers');

$consumer = Kafka::createConsumer([$topic], 'loss-fds')
  ->withBrokers($broker)
  ->withHandler(
    function (KafkaConsumerMessage $message) {
	    dd($message);
    }
  )
  ->stopAfterLastMessage()
  ->build()
  ->consume();
``` 

The consumer prints no message (even tried writing to Log and dd() method - still nothing) when using stopAfterLastMessage().

**Comment by mateusjunges** [comment] 2024-01-23 20:23
I just tried to reproduce this with the latest `v1.13.8` and `stopAfterLastMessage` is working as expected. This is my consumer code:


```php
$consumer = Kafka::createConsumer(brokers: 'localhost:9092')
    ->subscribe('^test[0-9]_.*')
    ->withHandler(function (ConsumedMessage $message) 
        $log = [
            'body' => $message->getBody(),
            'partition' => $message->getPartition(),
            'key' => $message->getKey(),
        ];
        $this->info(json_encode($log));
    })
    ->withOption('auto.offset.reset', 'earliest')
    ->stopAfterLastMessage()
    ->build()
    ->onStopConsuming(function () {
        $this->line('Stop consuming now');
        $this->newLine();
    });

$consumer->consume();
```

Closing this for now as I can't reproduce it. Feel free to open another issue if you are still having trouble, and please include a link to a repo where I can reproduce the issue.

**Closed by mateusjunges** 2024-01-23 20:23 UTC
Labels: bug
