### ISSUE TITLE
Getting a timeout issue, while trying to publish a message.

### ISSUE THREAD

**Issue by sazibuddin** [mateusjunges/laravel-kafka#272] opened 2024-03-20 06:56 UTC
**Here is my code to publish the message**
```
Kafka::publishOn('email_topic')
      ->withBodyKey('foo', 'bar')
      ->withHeaders([
          'foo-header' => 'foo-value'
      ])
      ->send();
```
And I'm using credentials from [confluent cloud](https://confluent.cloud/).
This is my broker address _KAFKA_BROKERS="pkc-12576z.us-west2.gcp.confluent.cloud:9092"_

When I'm trying to send a message, I get this timeout error while my default timeout setting is 50000.

```
"message": "Your message could not be published. Flush returned with error code -185: 'Local: Timed out'",
"exception": "Junges\\Kafka\\Exceptions\\CouldNotPublishMessage",
"file": "/opt/lampp/htdocs/office/quotation-ms/vendor/mateusjunges/laravel-kafka/src/Exceptions/CouldNotPublishMessage.php",
"line": 17,
```
 Thanks you

**Comment by mateusjunges** [comment] 2024-03-20 12:32
which version of this package and laravel are you using?

**Comment by sazibuddin** [comment] 2024-03-20 12:54
@mateusjunges 
"laravel/framework": "^10.10"
 "mateusjunges/laravel-kafka": "^1.13"

**Comment by sazibuddin** [comment] 2024-03-21 06:33
@mateusjunges could you please help me with that?

**Comment by anik6amtech** [comment] 2024-03-23 06:32
any one solved thisissue??

**Comment by mateusjunges** [comment] 2024-03-23 16:36
Hi 👋 I'm taking a look on this one now

**Comment by mateusjunges** [comment] 2024-03-23 17:21
Ok, I installed this package on a fresh laravel app. Created a basic consumer and was able to consume messages from confluent cloud:

![image](https://github.com/mateusjunges/laravel-kafka/assets/19756164/e343cd4b-5c10-48c2-bf9f-09903c2855ee)



This is my consumer code:


```php
$consumer = Kafka::createConsumer(brokers: 'pkc-12576z.us-west2.gcp.confluent.cloud:9092')
    ->subscribe('confluent')
    ->withHandler(function (ConsumedMessage $message) {
        $log = [
            'body' => $message->getBody(),
            'partition' => $message->getPartition(),
            'key' => $message->getKey(),
            'topic' => $message->getTopicName(),
        ];
    })
    ->withOption('topic.metadata.refresh.interval.ms', '2000')
    ->withSasl(
        new Sasl(
            username: 'QEZLZVT5OZOAYEKI',
            password: 'is/knYsCmPzNECWuI++/B+ygHs6AjKwDhZzlS7TbHDO/aGtq+/fzVTr8pjmr/L1r',
            mechanisms: 'PLAIN',
            securityProtocol: 'SASL_SSL'
        )
    )
    ->build()
    ->onStopConsuming(function () {
        $this->line('Stop consuming now');
        $this->newLine();
    });

$consumer->consume();
```

I also tested producing messages from my laravel app to the kafka cluster and it works just fine. I think you are probably missing some SASL configuration.

**Comment by mateusjunges** [comment] 2024-03-24 05:28
Closing this now since I can't reproduce it.

**Closed by mateusjunges** 2024-03-24 05:28 UTC
Labels: question
