### ISSUE TITLE
 Call to undefined method RdKafka\ProducerTopic::producev() 

### ISSUE THREAD

**Issue by dilip-E2** [mateusjunges/laravel-kafka#10] opened 2021-10-29 14:25 UTC
Hello,

I am getting error " Call to undefined method RdKafka\ProducerTopic::producev() " on creating producer.
i have also installed librdkafka using command "$ apt install librdkafka-dev"

I am using below environment.
PHP : 8.0.12
OS : Linux
rdkafka : 5.0.0 

Thanks,
Dilip
![Screenshot from 2021-10-29 19-54-46](https://user-images.githubusercontent.com/69678247/139452255-26108c24-1580-4cf1-8bda-b10d5d4d4c6d.png)

**Comment by mateusjunges** [comment] 2021-10-30 06:08
Hi @dilip-E2 
can you show me your code? I installed the package in a fresh laravel project and it works fine. Here is my working example:

My `ProducerController`:
```php
namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Junges\Kafka\Facades\Kafka;

class ProducerController
{
    public function __invoke()
    {
        Kafka::publishOn('localhost:9092', 'test_topic')
            ->withBodyKey('foo', 'bar')
            ->send();

        return response('ok');
    }
}
```

Routes:
```php
Route::get('produce', \App\Http\Controllers\ProducerController::class);
```

And this is the published message
![Screenshot from 2021-10-30 00-08-02](https://user-images.githubusercontent.com/19756164/139522511-88e07086-7f44-4d9f-bacb-2da1bbb239b2.png)
:

**Comment by elgibor-solution** [comment] 2021-10-30 14:14
@mateusjunges I also get same issue, below are my code

`
function publishMessage($type, $data, $whereQuery=false) {

    $headers = [
        "emr_service_id" => $this->tenantId,
        'user_id' => $this->user->id,
        'tenant_id' => $this->tenantId,
        'phone' => $this->user->phone,
        'message_type' => "TRANSACTION",
        'transaction_type' => $type
    ];

    $body = [
        "transaction_id" => uniqid(),
        "db_name" => \DB::connection()->getDatabaseName(),
        "table" => "es_patients",
        "data" => $data
    ];

    if ($whereQuery) {
        $body["where_query"] = $whereQuery;
    }

    $message = new Message($this->kafkaTopic, 0, $headers, $body);

    $producer = Kafka::publishOn('broker', $this->kafkaTopic)
                    ->withMessage($message)
                    ->send();

    $producer->send();
}
`

**Comment by mateusjunges** [comment] 2021-10-30 14:59
@elgibor-solution your code will throw an error because you are calling `send` on bool here:
```php
$producer->send()
```

You already called `send()` here:
```php
Kafka::publishOn('broker', $this->kafkaTopic)
    ->withMessage($message)
    ->send()
```

You don't need to calll `send` twice.

Also, i still can't reproduce the `Call to undefined method RdKafka\ProducerTopic::producev()` error.

**Comment by elgibor-solution** [comment] 2021-10-30 16:35
@mateusjunges 

please ignore the last "send", it's because i do debug.

The issue occured because the librdkafka version is under 0.11.4, i upgrade the version and the issue resolved.

But when i try to send, i got below error instead

`    "message": "",
    "exception": "Mockery\\Exception",
    "file": "/var/www/vendor/mateusjunges/laravel-kafka/src/Producers/Producer.php",
    "line": 74,
    "trace": [
        {
            "file": "/var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php",
            "line": 234,
            "function": "Junges\\Kafka\\Producers\\{closure}",
            "class": "Junges\\Kafka\\Producers\\Producer",
            "type": "->"
        },
        {
            "file": "/var/www/vendor/mateusjunges/laravel-kafka/src/Producers/Producer.php",
            "line": 75,
            "function": "retry"
        },
        {
            "file": "/var/www/vendor/mateusjunges/laravel-kafka/src/Producers/ProducerBuilder.php",
            "line": 142,
            "function": "produce",
            "class": "Junges\\Kafka\\Producers\\Producer",
            "type": "->"
        },`

Can you kindly advice?

**Comment by mateusjunges** [comment] 2021-10-31 06:17
Hi @elgibor-solution, is it working fine right now? Anything i can help you with?
@dilip-E2 let me know if @elgibor-solution solution works out for you.

**Comment by elgibor-solution** [comment] 2021-11-01 02:10
@mateusjunges It's working fine now, thanks!

**Comment by mateusjunges** [comment] 2021-11-01 02:56
Ok. @dilip-E2 i'm closing this assuming @elgibor-solution solutions solves your problem. Feel free to reopen this or create another one if you are still experiencing issues.

**Closed by mateusjunges** 2021-11-01 02:56 UTC
Labels: needs more info

**Comment by dilip-E2** [comment] 2021-11-01 05:31
@mateusjunges @elgibor-solution thanks for suppoert.

Below is my ubantu version 
Ubuntu 18.04.6 LTS

When i am trying to upgrade librdkafka it is giving me the latest version as 0.11.3, so is there any Ubantu version dependency for librdkafka 0.11.4?

Below is my librdkafka-dev information

$ sudo apt show librdkafka-dev
Package: librdkafka-dev
Version: 0.11.3-1build1
Priority: optional
Section: universe/libdevel
Source: librdkafka
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Faidon Liambotis <paravoid@debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 2,113 kB
Depends: librdkafka++1 (= 0.11.3-1build1), librdkafka1 (= 0.11.3-1build1)
Homepage: https://github.com/edenhill/librdkafka
Download-Size: 387 kB

Thanks,
Dilip

**Comment by elgibor-solution** [comment] 2021-11-01 06:01
> @mateusjunges @elgibor-solution thanks for suppoert.
> 
> Below is my ubantu version Ubuntu 18.04.6 LTS
> 
> When i am trying to upgrade librdkafka it is giving me the latest version as 0.11.3, so is there any Ubantu version dependency for librdkafka 0.11.4?
> 
> Can you please help me to upgrade librdkafka to 0.11.4?
> 
> Below is my librdkafka-dev information
> 
> $ sudo apt show librdkafka-dev Package: librdkafka-dev Version: 0.11.3-1build1 Priority: optional Section: universe/libdevel Source: librdkafka Origin: Ubuntu Maintainer: Ubuntu Developers [ubuntu-devel-discuss@lists.ubuntu.com](mailto:ubuntu-devel-discuss@lists.ubuntu.com) Original-Maintainer: Faidon Liambotis [paravoid@debian.org](mailto:paravoid@debian.org) Bugs: https://bugs.launchpad.net/ubuntu/+filebug Installed-Size: 2,113 kB Depends: librdkafka++1 (= 0.11.3-1build1), librdkafka1 (= 0.11.3-1build1) Homepage: https://github.com/edenhill/librdkafka Download-Size: 387 kB
> 
> Thanks, Dilip

@dilip-E2 I update the ubuntu into 20.04 to resolve that

**Comment by mateusjunges** [comment] 2021-11-01 12:50
@dilip-E2 i'm using version 1.2.1 on ubuntu 20.04.3 at this moment.
